//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace="tempuri.org")]

namespace tempuri.org
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUnsignedInt", Namespace="http://tempuri.org/", ItemName="unsignedInt")]
    public class ArrayOfUnsignedInt : System.Collections.Generic.List<uint>
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
    BuyCamulativeResponse BuyCamulative(BuyCamulativeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
    System.Threading.Tasks.Task<BuyCamulativeResponse> BuyCamulativeAsync(BuyCamulativeRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
    BuyInvestmentResponse BuyInvestment(BuyInvestmentRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
    System.Threading.Tasks.Task<BuyInvestmentResponse> BuyInvestmentAsync(BuyInvestmentRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
    PayInvestPercentsResponse PayInvestPercents(PayInvestPercentsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
    System.Threading.Tasks.Task<PayInvestPercentsResponse> PayInvestPercentsAsync(PayInvestPercentsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
    bool IsAllowCreateNewPlace(uint marketingId, uint partnerId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
    System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId);
    
    // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
    CreateTechPlaceResponse CreateTechPlace(CreateTechPlaceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
    System.Threading.Tasks.Task<CreateTechPlaceResponse> CreateTechPlaceAsync(CreateTechPlaceRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем objectName из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlace", ReplyAction="http://tempuri.org/IService1/CreatePlaceResponse")]
    CreatePlaceResponse CreatePlace(CreatePlaceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlace", ReplyAction="http://tempuri.org/IService1/CreatePlaceResponse")]
    System.Threading.Tasks.Task<CreatePlaceResponse> CreatePlaceAsync(CreatePlaceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
    int UpdateBalances();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
    System.Threading.Tasks.Task<int> UpdateBalancesAsync();
    
    // CODEGEN: Контракт генерации сообщений с именем wallet из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
    ConfirmWithdrawalResponse ConfirmWithdrawal(ConfirmWithdrawalRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
    System.Threading.Tasks.Task<ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(ConfirmWithdrawalRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем comment из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
    CancelWithdrawalResponse CancelWithdrawal(CancelWithdrawalRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
    System.Threading.Tasks.Task<CancelWithdrawalResponse> CancelWithdrawalAsync(CancelWithdrawalRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем investments из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
    UnionInvestmentsResponse UnionInvestments(UnionInvestmentsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
    System.Threading.Tasks.Task<UnionInvestmentsResponse> UnionInvestmentsAsync(UnionInvestmentsRequest request);
    
    // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
    TerminateInvestmentResponse TerminateInvestment(TerminateInvestmentRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
    System.Threading.Tasks.Task<TerminateInvestmentResponse> TerminateInvestmentAsync(TerminateInvestmentRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BuyCamulativeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulative", Namespace="http://tempuri.org/", Order=0)]
    public BuyCamulativeRequestBody Body;
    
    public BuyCamulativeRequest()
    {
    }
    
    public BuyCamulativeRequest(BuyCamulativeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class BuyCamulativeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint marketingId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public uint partnerId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public decimal sum;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string user;
    
    public BuyCamulativeRequestBody()
    {
    }
    
    public BuyCamulativeRequestBody(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user)
    {
        this.companyId = companyId;
        this.marketingId = marketingId;
        this.partnerId = partnerId;
        this.sum = sum;
        this.date = date;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BuyCamulativeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulativeResponse", Namespace="http://tempuri.org/", Order=0)]
    public BuyCamulativeResponseBody Body;
    
    public BuyCamulativeResponse()
    {
    }
    
    public BuyCamulativeResponse(BuyCamulativeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class BuyCamulativeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint BuyCamulativeResult;
    
    public BuyCamulativeResponseBody()
    {
    }
    
    public BuyCamulativeResponseBody(uint BuyCamulativeResult)
    {
        this.BuyCamulativeResult = BuyCamulativeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BuyInvestmentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestment", Namespace="http://tempuri.org/", Order=0)]
    public BuyInvestmentRequestBody Body;
    
    public BuyInvestmentRequest()
    {
    }
    
    public BuyInvestmentRequest(BuyInvestmentRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class BuyInvestmentRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint camulativeMarketingId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public uint partnerId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public decimal sum;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public bool isProlonged;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public bool isCreateNewPlace;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    public string user;
    
    public BuyInvestmentRequestBody()
    {
    }
    
    public BuyInvestmentRequestBody(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user)
    {
        this.companyId = companyId;
        this.camulativeMarketingId = camulativeMarketingId;
        this.partnerId = partnerId;
        this.sum = sum;
        this.isProlonged = isProlonged;
        this.isCreateNewPlace = isCreateNewPlace;
        this.date = date;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BuyInvestmentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
    public BuyInvestmentResponseBody Body;
    
    public BuyInvestmentResponse()
    {
    }
    
    public BuyInvestmentResponse(BuyInvestmentResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class BuyInvestmentResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint BuyInvestmentResult;
    
    public BuyInvestmentResponseBody()
    {
    }
    
    public BuyInvestmentResponseBody(uint BuyInvestmentResult)
    {
        this.BuyInvestmentResult = BuyInvestmentResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PayInvestPercentsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercents", Namespace="http://tempuri.org/", Order=0)]
    public PayInvestPercentsRequestBody Body;
    
    public PayInvestPercentsRequest()
    {
    }
    
    public PayInvestPercentsRequest(PayInvestPercentsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class PayInvestPercentsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string user;
    
    public PayInvestPercentsRequestBody()
    {
    }
    
    public PayInvestPercentsRequestBody(System.DateTime date, uint companyId, string user)
    {
        this.date = date;
        this.companyId = companyId;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PayInvestPercentsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercentsResponse", Namespace="http://tempuri.org/", Order=0)]
    public PayInvestPercentsResponseBody Body;
    
    public PayInvestPercentsResponse()
    {
    }
    
    public PayInvestPercentsResponse(PayInvestPercentsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class PayInvestPercentsResponseBody
{
    
    public PayInvestPercentsResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateTechPlaceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlace", Namespace="http://tempuri.org/", Order=0)]
    public CreateTechPlaceRequestBody Body;
    
    public CreateTechPlaceRequest()
    {
    }
    
    public CreateTechPlaceRequest(CreateTechPlaceRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateTechPlaceRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint marketingId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string user;
    
    public CreateTechPlaceRequestBody()
    {
    }
    
    public CreateTechPlaceRequestBody(uint companyId, uint marketingId, System.DateTime date, string user)
    {
        this.companyId = companyId;
        this.marketingId = marketingId;
        this.date = date;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateTechPlaceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlaceResponse", Namespace="http://tempuri.org/", Order=0)]
    public CreateTechPlaceResponseBody Body;
    
    public CreateTechPlaceResponse()
    {
    }
    
    public CreateTechPlaceResponse(CreateTechPlaceResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateTechPlaceResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint CreateTechPlaceResult;
    
    public CreateTechPlaceResponseBody()
    {
    }
    
    public CreateTechPlaceResponseBody(uint CreateTechPlaceResult)
    {
        this.CreateTechPlaceResult = CreateTechPlaceResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreatePlaceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePlace", Namespace="http://tempuri.org/", Order=0)]
    public CreatePlaceRequestBody Body;
    
    public CreatePlaceRequest()
    {
    }
    
    public CreatePlaceRequest(CreatePlaceRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreatePlaceRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint marketingId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public uint partnerId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string objectName;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string alias;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public decimal sum;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    public string user;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
    public uint activePlaceId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
    public int pos;
    
    public CreatePlaceRequestBody()
    {
    }
    
    public CreatePlaceRequestBody(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos)
    {
        this.companyId = companyId;
        this.marketingId = marketingId;
        this.partnerId = partnerId;
        this.objectName = objectName;
        this.alias = alias;
        this.sum = sum;
        this.date = date;
        this.user = user;
        this.activePlaceId = activePlaceId;
        this.pos = pos;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreatePlaceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePlaceResponse", Namespace="http://tempuri.org/", Order=0)]
    public CreatePlaceResponseBody Body;
    
    public CreatePlaceResponse()
    {
    }
    
    public CreatePlaceResponse(CreatePlaceResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreatePlaceResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint CreatePlaceResult;
    
    public CreatePlaceResponseBody()
    {
    }
    
    public CreatePlaceResponseBody(uint CreatePlaceResult)
    {
        this.CreatePlaceResult = CreatePlaceResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ConfirmWithdrawalRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawal", Namespace="http://tempuri.org/", Order=0)]
    public ConfirmWithdrawalRequestBody Body;
    
    public ConfirmWithdrawalRequest()
    {
    }
    
    public ConfirmWithdrawalRequest(ConfirmWithdrawalRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ConfirmWithdrawalRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint id_object;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string wallet;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string tag;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string comment;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string user;
    
    public ConfirmWithdrawalRequestBody()
    {
    }
    
    public ConfirmWithdrawalRequestBody(uint id_object, string wallet, string tag, string comment, string user)
    {
        this.id_object = id_object;
        this.wallet = wallet;
        this.tag = tag;
        this.comment = comment;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ConfirmWithdrawalResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
    public ConfirmWithdrawalResponseBody Body;
    
    public ConfirmWithdrawalResponse()
    {
    }
    
    public ConfirmWithdrawalResponse(ConfirmWithdrawalResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ConfirmWithdrawalResponseBody
{
    
    public ConfirmWithdrawalResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CancelWithdrawalRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawal", Namespace="http://tempuri.org/", Order=0)]
    public CancelWithdrawalRequestBody Body;
    
    public CancelWithdrawalRequest()
    {
    }
    
    public CancelWithdrawalRequest(CancelWithdrawalRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CancelWithdrawalRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint id_object;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string comment;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string user;
    
    public CancelWithdrawalRequestBody()
    {
    }
    
    public CancelWithdrawalRequestBody(uint id_object, string comment, string user)
    {
        this.id_object = id_object;
        this.comment = comment;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CancelWithdrawalResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
    public CancelWithdrawalResponseBody Body;
    
    public CancelWithdrawalResponse()
    {
    }
    
    public CancelWithdrawalResponse(CancelWithdrawalResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class CancelWithdrawalResponseBody
{
    
    public CancelWithdrawalResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UnionInvestmentsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestments", Namespace="http://tempuri.org/", Order=0)]
    public UnionInvestmentsRequestBody Body;
    
    public UnionInvestmentsRequest()
    {
    }
    
    public UnionInvestmentsRequest(UnionInvestmentsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UnionInvestmentsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint partnerId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public decimal sum;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public tempuri.org.ArrayOfUnsignedInt investments;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string user;
    
    public UnionInvestmentsRequestBody()
    {
    }
    
    public UnionInvestmentsRequestBody(uint companyId, uint partnerId, decimal sum, tempuri.org.ArrayOfUnsignedInt investments, System.DateTime date, string user)
    {
        this.companyId = companyId;
        this.partnerId = partnerId;
        this.sum = sum;
        this.investments = investments;
        this.date = date;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UnionInvestmentsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestmentsResponse", Namespace="http://tempuri.org/", Order=0)]
    public UnionInvestmentsResponseBody Body;
    
    public UnionInvestmentsResponse()
    {
    }
    
    public UnionInvestmentsResponse(UnionInvestmentsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UnionInvestmentsResponseBody
{
    
    public UnionInvestmentsResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TerminateInvestmentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestment", Namespace="http://tempuri.org/", Order=0)]
    public TerminateInvestmentRequestBody Body;
    
    public TerminateInvestmentRequest()
    {
    }
    
    public TerminateInvestmentRequest(TerminateInvestmentRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class TerminateInvestmentRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public uint companyId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public uint partnerId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public uint investmentId;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public decimal returnSum;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public System.DateTime date;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string user;
    
    public TerminateInvestmentRequestBody()
    {
    }
    
    public TerminateInvestmentRequestBody(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user)
    {
        this.companyId = companyId;
        this.partnerId = partnerId;
        this.investmentId = investmentId;
        this.returnSum = returnSum;
        this.date = date;
        this.user = user;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class TerminateInvestmentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
    public TerminateInvestmentResponseBody Body;
    
    public TerminateInvestmentResponse()
    {
    }
    
    public TerminateInvestmentResponse(TerminateInvestmentResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class TerminateInvestmentResponseBody
{
    
    public TerminateInvestmentResponseBody()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BuyCamulativeResponse IService1.BuyCamulative(BuyCamulativeRequest request)
    {
        return base.Channel.BuyCamulative(request);
    }
    
    public uint BuyCamulative(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user)
    {
        BuyCamulativeRequest inValue = new BuyCamulativeRequest();
        inValue.Body = new BuyCamulativeRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        BuyCamulativeResponse retVal = ((IService1)(this)).BuyCamulative(inValue);
        return retVal.Body.BuyCamulativeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<BuyCamulativeResponse> IService1.BuyCamulativeAsync(BuyCamulativeRequest request)
    {
        return base.Channel.BuyCamulativeAsync(request);
    }
    
    public System.Threading.Tasks.Task<BuyCamulativeResponse> BuyCamulativeAsync(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user)
    {
        BuyCamulativeRequest inValue = new BuyCamulativeRequest();
        inValue.Body = new BuyCamulativeRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        return ((IService1)(this)).BuyCamulativeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BuyInvestmentResponse IService1.BuyInvestment(BuyInvestmentRequest request)
    {
        return base.Channel.BuyInvestment(request);
    }
    
    public uint BuyInvestment(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user)
    {
        BuyInvestmentRequest inValue = new BuyInvestmentRequest();
        inValue.Body = new BuyInvestmentRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.camulativeMarketingId = camulativeMarketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.isProlonged = isProlonged;
        inValue.Body.isCreateNewPlace = isCreateNewPlace;
        inValue.Body.date = date;
        inValue.Body.user = user;
        BuyInvestmentResponse retVal = ((IService1)(this)).BuyInvestment(inValue);
        return retVal.Body.BuyInvestmentResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<BuyInvestmentResponse> IService1.BuyInvestmentAsync(BuyInvestmentRequest request)
    {
        return base.Channel.BuyInvestmentAsync(request);
    }
    
    public System.Threading.Tasks.Task<BuyInvestmentResponse> BuyInvestmentAsync(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user)
    {
        BuyInvestmentRequest inValue = new BuyInvestmentRequest();
        inValue.Body = new BuyInvestmentRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.camulativeMarketingId = camulativeMarketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.isProlonged = isProlonged;
        inValue.Body.isCreateNewPlace = isCreateNewPlace;
        inValue.Body.date = date;
        inValue.Body.user = user;
        return ((IService1)(this)).BuyInvestmentAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PayInvestPercentsResponse IService1.PayInvestPercents(PayInvestPercentsRequest request)
    {
        return base.Channel.PayInvestPercents(request);
    }
    
    public void PayInvestPercents(System.DateTime date, uint companyId, string user)
    {
        PayInvestPercentsRequest inValue = new PayInvestPercentsRequest();
        inValue.Body = new PayInvestPercentsRequestBody();
        inValue.Body.date = date;
        inValue.Body.companyId = companyId;
        inValue.Body.user = user;
        PayInvestPercentsResponse retVal = ((IService1)(this)).PayInvestPercents(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PayInvestPercentsResponse> IService1.PayInvestPercentsAsync(PayInvestPercentsRequest request)
    {
        return base.Channel.PayInvestPercentsAsync(request);
    }
    
    public System.Threading.Tasks.Task<PayInvestPercentsResponse> PayInvestPercentsAsync(System.DateTime date, uint companyId, string user)
    {
        PayInvestPercentsRequest inValue = new PayInvestPercentsRequest();
        inValue.Body = new PayInvestPercentsRequestBody();
        inValue.Body.date = date;
        inValue.Body.companyId = companyId;
        inValue.Body.user = user;
        return ((IService1)(this)).PayInvestPercentsAsync(inValue);
    }
    
    public bool IsAllowCreateNewPlace(uint marketingId, uint partnerId)
    {
        return base.Channel.IsAllowCreateNewPlace(marketingId, partnerId);
    }
    
    public System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId)
    {
        return base.Channel.IsAllowCreateNewPlaceAsync(marketingId, partnerId);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateTechPlaceResponse IService1.CreateTechPlace(CreateTechPlaceRequest request)
    {
        return base.Channel.CreateTechPlace(request);
    }
    
    public uint CreateTechPlace(uint companyId, uint marketingId, System.DateTime date, string user)
    {
        CreateTechPlaceRequest inValue = new CreateTechPlaceRequest();
        inValue.Body = new CreateTechPlaceRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.date = date;
        inValue.Body.user = user;
        CreateTechPlaceResponse retVal = ((IService1)(this)).CreateTechPlace(inValue);
        return retVal.Body.CreateTechPlaceResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateTechPlaceResponse> IService1.CreateTechPlaceAsync(CreateTechPlaceRequest request)
    {
        return base.Channel.CreateTechPlaceAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateTechPlaceResponse> CreateTechPlaceAsync(uint companyId, uint marketingId, System.DateTime date, string user)
    {
        CreateTechPlaceRequest inValue = new CreateTechPlaceRequest();
        inValue.Body = new CreateTechPlaceRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.date = date;
        inValue.Body.user = user;
        return ((IService1)(this)).CreateTechPlaceAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreatePlaceResponse IService1.CreatePlace(CreatePlaceRequest request)
    {
        return base.Channel.CreatePlace(request);
    }
    
    public uint CreatePlace(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos)
    {
        CreatePlaceRequest inValue = new CreatePlaceRequest();
        inValue.Body = new CreatePlaceRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.objectName = objectName;
        inValue.Body.alias = alias;
        inValue.Body.sum = sum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        inValue.Body.activePlaceId = activePlaceId;
        inValue.Body.pos = pos;
        CreatePlaceResponse retVal = ((IService1)(this)).CreatePlace(inValue);
        return retVal.Body.CreatePlaceResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreatePlaceResponse> IService1.CreatePlaceAsync(CreatePlaceRequest request)
    {
        return base.Channel.CreatePlaceAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreatePlaceResponse> CreatePlaceAsync(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos)
    {
        CreatePlaceRequest inValue = new CreatePlaceRequest();
        inValue.Body = new CreatePlaceRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.marketingId = marketingId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.objectName = objectName;
        inValue.Body.alias = alias;
        inValue.Body.sum = sum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        inValue.Body.activePlaceId = activePlaceId;
        inValue.Body.pos = pos;
        return ((IService1)(this)).CreatePlaceAsync(inValue);
    }
    
    public int UpdateBalances()
    {
        return base.Channel.UpdateBalances();
    }
    
    public System.Threading.Tasks.Task<int> UpdateBalancesAsync()
    {
        return base.Channel.UpdateBalancesAsync();
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ConfirmWithdrawalResponse IService1.ConfirmWithdrawal(ConfirmWithdrawalRequest request)
    {
        return base.Channel.ConfirmWithdrawal(request);
    }
    
    public void ConfirmWithdrawal(uint id_object, string wallet, string tag, string comment, string user)
    {
        ConfirmWithdrawalRequest inValue = new ConfirmWithdrawalRequest();
        inValue.Body = new ConfirmWithdrawalRequestBody();
        inValue.Body.id_object = id_object;
        inValue.Body.wallet = wallet;
        inValue.Body.tag = tag;
        inValue.Body.comment = comment;
        inValue.Body.user = user;
        ConfirmWithdrawalResponse retVal = ((IService1)(this)).ConfirmWithdrawal(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ConfirmWithdrawalResponse> IService1.ConfirmWithdrawalAsync(ConfirmWithdrawalRequest request)
    {
        return base.Channel.ConfirmWithdrawalAsync(request);
    }
    
    public System.Threading.Tasks.Task<ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(uint id_object, string wallet, string tag, string comment, string user)
    {
        ConfirmWithdrawalRequest inValue = new ConfirmWithdrawalRequest();
        inValue.Body = new ConfirmWithdrawalRequestBody();
        inValue.Body.id_object = id_object;
        inValue.Body.wallet = wallet;
        inValue.Body.tag = tag;
        inValue.Body.comment = comment;
        inValue.Body.user = user;
        return ((IService1)(this)).ConfirmWithdrawalAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CancelWithdrawalResponse IService1.CancelWithdrawal(CancelWithdrawalRequest request)
    {
        return base.Channel.CancelWithdrawal(request);
    }
    
    public void CancelWithdrawal(uint id_object, string comment, string user)
    {
        CancelWithdrawalRequest inValue = new CancelWithdrawalRequest();
        inValue.Body = new CancelWithdrawalRequestBody();
        inValue.Body.id_object = id_object;
        inValue.Body.comment = comment;
        inValue.Body.user = user;
        CancelWithdrawalResponse retVal = ((IService1)(this)).CancelWithdrawal(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CancelWithdrawalResponse> IService1.CancelWithdrawalAsync(CancelWithdrawalRequest request)
    {
        return base.Channel.CancelWithdrawalAsync(request);
    }
    
    public System.Threading.Tasks.Task<CancelWithdrawalResponse> CancelWithdrawalAsync(uint id_object, string comment, string user)
    {
        CancelWithdrawalRequest inValue = new CancelWithdrawalRequest();
        inValue.Body = new CancelWithdrawalRequestBody();
        inValue.Body.id_object = id_object;
        inValue.Body.comment = comment;
        inValue.Body.user = user;
        return ((IService1)(this)).CancelWithdrawalAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UnionInvestmentsResponse IService1.UnionInvestments(UnionInvestmentsRequest request)
    {
        return base.Channel.UnionInvestments(request);
    }
    
    public void UnionInvestments(uint companyId, uint partnerId, decimal sum, tempuri.org.ArrayOfUnsignedInt investments, System.DateTime date, string user)
    {
        UnionInvestmentsRequest inValue = new UnionInvestmentsRequest();
        inValue.Body = new UnionInvestmentsRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.investments = investments;
        inValue.Body.date = date;
        inValue.Body.user = user;
        UnionInvestmentsResponse retVal = ((IService1)(this)).UnionInvestments(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<UnionInvestmentsResponse> IService1.UnionInvestmentsAsync(UnionInvestmentsRequest request)
    {
        return base.Channel.UnionInvestmentsAsync(request);
    }
    
    public System.Threading.Tasks.Task<UnionInvestmentsResponse> UnionInvestmentsAsync(uint companyId, uint partnerId, decimal sum, tempuri.org.ArrayOfUnsignedInt investments, System.DateTime date, string user)
    {
        UnionInvestmentsRequest inValue = new UnionInvestmentsRequest();
        inValue.Body = new UnionInvestmentsRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.sum = sum;
        inValue.Body.investments = investments;
        inValue.Body.date = date;
        inValue.Body.user = user;
        return ((IService1)(this)).UnionInvestmentsAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TerminateInvestmentResponse IService1.TerminateInvestment(TerminateInvestmentRequest request)
    {
        return base.Channel.TerminateInvestment(request);
    }
    
    public void TerminateInvestment(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user)
    {
        TerminateInvestmentRequest inValue = new TerminateInvestmentRequest();
        inValue.Body = new TerminateInvestmentRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.investmentId = investmentId;
        inValue.Body.returnSum = returnSum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        TerminateInvestmentResponse retVal = ((IService1)(this)).TerminateInvestment(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<TerminateInvestmentResponse> IService1.TerminateInvestmentAsync(TerminateInvestmentRequest request)
    {
        return base.Channel.TerminateInvestmentAsync(request);
    }
    
    public System.Threading.Tasks.Task<TerminateInvestmentResponse> TerminateInvestmentAsync(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user)
    {
        TerminateInvestmentRequest inValue = new TerminateInvestmentRequest();
        inValue.Body = new TerminateInvestmentRequestBody();
        inValue.Body.companyId = companyId;
        inValue.Body.partnerId = partnerId;
        inValue.Body.investmentId = investmentId;
        inValue.Body.returnSum = returnSum;
        inValue.Body.date = date;
        inValue.Body.user = user;
        return ((IService1)(this)).TerminateInvestmentAsync(inValue);
    }
}
