//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W2W.TaskEmail.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUnsignedInt", Namespace="http://tempuri.org/", ItemName="unsignedInt")]
    [System.SerializableAttribute()]
    public class ArrayOfUnsignedInt : System.Collections.Generic.List<uint> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
        W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse BuyCamulative(W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse> BuyCamulativeAsync(W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
        W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse BuyInvestment(W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse> BuyInvestmentAsync(W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
        W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse PayInvestPercents(W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse> PayInvestPercentsAsync(W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
        bool IsAllowCreateNewPlace(uint marketingId, uint partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
        System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId);
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
        W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse CreateTechPlace(W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse> CreateTechPlaceAsync(W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем objectName из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlace", ReplyAction="http://tempuri.org/IService1/CreatePlaceResponse")]
        W2W.TaskEmail.ServiceReference1.CreatePlaceResponse CreatePlace(W2W.TaskEmail.ServiceReference1.CreatePlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlace", ReplyAction="http://tempuri.org/IService1/CreatePlaceResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreatePlaceResponse> CreatePlaceAsync(W2W.TaskEmail.ServiceReference1.CreatePlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
        int UpdateBalances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
        System.Threading.Tasks.Task<int> UpdateBalancesAsync();
        
        // CODEGEN: Контракт генерации сообщений с именем wallet из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
        W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse ConfirmWithdrawal(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем comment из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
        W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse CancelWithdrawal(W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse> CancelWithdrawalAsync(W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем investments из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
        W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse UnionInvestments(W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse> UnionInvestmentsAsync(W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
        W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse TerminateInvestment(W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse> TerminateInvestmentAsync(W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем user из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmail", ReplyAction="http://tempuri.org/IService1/SendEmailResponse")]
        W2W.TaskEmail.ServiceReference1.SendEmailResponse SendEmail(W2W.TaskEmail.ServiceReference1.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmail", ReplyAction="http://tempuri.org/IService1/SendEmailResponse")]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.SendEmailResponse> SendEmailAsync(W2W.TaskEmail.ServiceReference1.SendEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyCamulativeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulative", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.BuyCamulativeRequestBody Body;
        
        public BuyCamulativeRequest() {
        }
        
        public BuyCamulativeRequest(W2W.TaskEmail.ServiceReference1.BuyCamulativeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyCamulativeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint marketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        public BuyCamulativeRequestBody() {
        }
        
        public BuyCamulativeRequestBody(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            this.companyId = companyId;
            this.marketingId = marketingId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyCamulativeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulativeResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.BuyCamulativeResponseBody Body;
        
        public BuyCamulativeResponse() {
        }
        
        public BuyCamulativeResponse(W2W.TaskEmail.ServiceReference1.BuyCamulativeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyCamulativeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint BuyCamulativeResult;
        
        public BuyCamulativeResponseBody() {
        }
        
        public BuyCamulativeResponseBody(uint BuyCamulativeResult) {
            this.BuyCamulativeResult = BuyCamulativeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyInvestmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestment", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.BuyInvestmentRequestBody Body;
        
        public BuyInvestmentRequest() {
        }
        
        public BuyInvestmentRequest(W2W.TaskEmail.ServiceReference1.BuyInvestmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyInvestmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint camulativeMarketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isProlonged;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isCreateNewPlace;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string user;
        
        public BuyInvestmentRequestBody() {
        }
        
        public BuyInvestmentRequestBody(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            this.companyId = companyId;
            this.camulativeMarketingId = camulativeMarketingId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.isProlonged = isProlonged;
            this.isCreateNewPlace = isCreateNewPlace;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyInvestmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.BuyInvestmentResponseBody Body;
        
        public BuyInvestmentResponse() {
        }
        
        public BuyInvestmentResponse(W2W.TaskEmail.ServiceReference1.BuyInvestmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyInvestmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint BuyInvestmentResult;
        
        public BuyInvestmentResponseBody() {
        }
        
        public BuyInvestmentResponseBody(uint BuyInvestmentResult) {
            this.BuyInvestmentResult = BuyInvestmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayInvestPercentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercents", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequestBody Body;
        
        public PayInvestPercentsRequest() {
        }
        
        public PayInvestPercentsRequest(W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayInvestPercentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public PayInvestPercentsRequestBody() {
        }
        
        public PayInvestPercentsRequestBody(System.DateTime date, uint companyId, string user) {
            this.date = date;
            this.companyId = companyId;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayInvestPercentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponseBody Body;
        
        public PayInvestPercentsResponse() {
        }
        
        public PayInvestPercentsResponse(W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayInvestPercentsResponseBody {
        
        public PayInvestPercentsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTechPlaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlace", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequestBody Body;
        
        public CreateTechPlaceRequest() {
        }
        
        public CreateTechPlaceRequest(W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTechPlaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint marketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string user;
        
        public CreateTechPlaceRequestBody() {
        }
        
        public CreateTechPlaceRequestBody(uint companyId, uint marketingId, System.DateTime date, string user) {
            this.companyId = companyId;
            this.marketingId = marketingId;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTechPlaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlaceResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponseBody Body;
        
        public CreateTechPlaceResponse() {
        }
        
        public CreateTechPlaceResponse(W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTechPlaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint CreateTechPlaceResult;
        
        public CreateTechPlaceResponseBody() {
        }
        
        public CreateTechPlaceResponseBody(uint CreateTechPlaceResult) {
            this.CreateTechPlaceResult = CreateTechPlaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePlaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePlace", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CreatePlaceRequestBody Body;
        
        public CreatePlaceRequest() {
        }
        
        public CreatePlaceRequest(W2W.TaskEmail.ServiceReference1.CreatePlaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePlaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint marketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string alias;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public uint activePlaceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int pos;
        
        public CreatePlaceRequestBody() {
        }
        
        public CreatePlaceRequestBody(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos) {
            this.companyId = companyId;
            this.marketingId = marketingId;
            this.partnerId = partnerId;
            this.objectName = objectName;
            this.alias = alias;
            this.sum = sum;
            this.date = date;
            this.user = user;
            this.activePlaceId = activePlaceId;
            this.pos = pos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePlaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePlaceResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CreatePlaceResponseBody Body;
        
        public CreatePlaceResponse() {
        }
        
        public CreatePlaceResponse(W2W.TaskEmail.ServiceReference1.CreatePlaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePlaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint CreatePlaceResult;
        
        public CreatePlaceResponseBody() {
        }
        
        public CreatePlaceResponseBody(uint CreatePlaceResult) {
            this.CreatePlaceResult = CreatePlaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawal", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequestBody Body;
        
        public ConfirmWithdrawalRequest() {
        }
        
        public ConfirmWithdrawalRequest(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint id_object;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string wallet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string user;
        
        public ConfirmWithdrawalRequestBody() {
        }
        
        public ConfirmWithdrawalRequestBody(uint id_object, string wallet, string tag, string comment, string user) {
            this.id_object = id_object;
            this.wallet = wallet;
            this.tag = tag;
            this.comment = comment;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmWithdrawalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponseBody Body;
        
        public ConfirmWithdrawalResponse() {
        }
        
        public ConfirmWithdrawalResponse(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConfirmWithdrawalResponseBody {
        
        public ConfirmWithdrawalResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawal", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequestBody Body;
        
        public CancelWithdrawalRequest() {
        }
        
        public CancelWithdrawalRequest(W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint id_object;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public CancelWithdrawalRequestBody() {
        }
        
        public CancelWithdrawalRequestBody(uint id_object, string comment, string user) {
            this.id_object = id_object;
            this.comment = comment;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelWithdrawalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponseBody Body;
        
        public CancelWithdrawalResponse() {
        }
        
        public CancelWithdrawalResponse(W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CancelWithdrawalResponseBody {
        
        public CancelWithdrawalResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnionInvestmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestments", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequestBody Body;
        
        public UnionInvestmentsRequest() {
        }
        
        public UnionInvestmentsRequest(W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnionInvestmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public W2W.TaskEmail.ServiceReference1.ArrayOfUnsignedInt investments;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        public UnionInvestmentsRequestBody() {
        }
        
        public UnionInvestmentsRequestBody(uint companyId, uint partnerId, decimal sum, W2W.TaskEmail.ServiceReference1.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            this.companyId = companyId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.investments = investments;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnionInvestmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponseBody Body;
        
        public UnionInvestmentsResponse() {
        }
        
        public UnionInvestmentsResponse(W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UnionInvestmentsResponseBody {
        
        public UnionInvestmentsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateInvestmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestment", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequestBody Body;
        
        public TerminateInvestmentRequest() {
        }
        
        public TerminateInvestmentRequest(W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TerminateInvestmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint investmentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal returnSum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<bool> isNotClose;
        
        public TerminateInvestmentRequestBody() {
        }
        
        public TerminateInvestmentRequestBody(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user, System.Nullable<bool> isNotClose) {
            this.companyId = companyId;
            this.partnerId = partnerId;
            this.investmentId = investmentId;
            this.returnSum = returnSum;
            this.date = date;
            this.user = user;
            this.isNotClose = isNotClose;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateInvestmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponseBody Body;
        
        public TerminateInvestmentResponse() {
        }
        
        public TerminateInvestmentResponse(W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TerminateInvestmentResponseBody {
        
        public TerminateInvestmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.SendEmailRequestBody Body;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(W2W.TaskEmail.ServiceReference1.SendEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        public SendEmailRequestBody() {
        }
        
        public SendEmailRequestBody(uint companyId, string user) {
            this.companyId = companyId;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public W2W.TaskEmail.ServiceReference1.SendEmailResponseBody Body;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(W2W.TaskEmail.ServiceReference1.SendEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendEmailResponseBody {
        
        public SendEmailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : W2W.TaskEmail.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<W2W.TaskEmail.ServiceReference1.IService1>, W2W.TaskEmail.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse W2W.TaskEmail.ServiceReference1.IService1.BuyCamulative(W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest request) {
            return base.Channel.BuyCamulative(request);
        }
        
        public uint BuyCamulative(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest inValue = new W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.BuyCamulativeRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).BuyCamulative(inValue);
            return retVal.Body.BuyCamulativeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse> W2W.TaskEmail.ServiceReference1.IService1.BuyCamulativeAsync(W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest request) {
            return base.Channel.BuyCamulativeAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyCamulativeResponse> BuyCamulativeAsync(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest inValue = new W2W.TaskEmail.ServiceReference1.BuyCamulativeRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.BuyCamulativeRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).BuyCamulativeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse W2W.TaskEmail.ServiceReference1.IService1.BuyInvestment(W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest request) {
            return base.Channel.BuyInvestment(request);
        }
        
        public uint BuyInvestment(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest inValue = new W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.BuyInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.camulativeMarketingId = camulativeMarketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.isProlonged = isProlonged;
            inValue.Body.isCreateNewPlace = isCreateNewPlace;
            inValue.Body.date = date;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).BuyInvestment(inValue);
            return retVal.Body.BuyInvestmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse> W2W.TaskEmail.ServiceReference1.IService1.BuyInvestmentAsync(W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest request) {
            return base.Channel.BuyInvestmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.BuyInvestmentResponse> BuyInvestmentAsync(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest inValue = new W2W.TaskEmail.ServiceReference1.BuyInvestmentRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.BuyInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.camulativeMarketingId = camulativeMarketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.isProlonged = isProlonged;
            inValue.Body.isCreateNewPlace = isCreateNewPlace;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).BuyInvestmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse W2W.TaskEmail.ServiceReference1.IService1.PayInvestPercents(W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest request) {
            return base.Channel.PayInvestPercents(request);
        }
        
        public void PayInvestPercents(System.DateTime date, uint companyId, string user) {
            W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest inValue = new W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequestBody();
            inValue.Body.date = date;
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).PayInvestPercents(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse> W2W.TaskEmail.ServiceReference1.IService1.PayInvestPercentsAsync(W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest request) {
            return base.Channel.PayInvestPercentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.PayInvestPercentsResponse> PayInvestPercentsAsync(System.DateTime date, uint companyId, string user) {
            W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest inValue = new W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.PayInvestPercentsRequestBody();
            inValue.Body.date = date;
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).PayInvestPercentsAsync(inValue);
        }
        
        public bool IsAllowCreateNewPlace(uint marketingId, uint partnerId) {
            return base.Channel.IsAllowCreateNewPlace(marketingId, partnerId);
        }
        
        public System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId) {
            return base.Channel.IsAllowCreateNewPlaceAsync(marketingId, partnerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse W2W.TaskEmail.ServiceReference1.IService1.CreateTechPlace(W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest request) {
            return base.Channel.CreateTechPlace(request);
        }
        
        public uint CreateTechPlace(uint companyId, uint marketingId, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest inValue = new W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.date = date;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CreateTechPlace(inValue);
            return retVal.Body.CreateTechPlaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse> W2W.TaskEmail.ServiceReference1.IService1.CreateTechPlaceAsync(W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest request) {
            return base.Channel.CreateTechPlaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreateTechPlaceResponse> CreateTechPlaceAsync(uint companyId, uint marketingId, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest inValue = new W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CreateTechPlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CreateTechPlaceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.CreatePlaceResponse W2W.TaskEmail.ServiceReference1.IService1.CreatePlace(W2W.TaskEmail.ServiceReference1.CreatePlaceRequest request) {
            return base.Channel.CreatePlace(request);
        }
        
        public uint CreatePlace(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos) {
            W2W.TaskEmail.ServiceReference1.CreatePlaceRequest inValue = new W2W.TaskEmail.ServiceReference1.CreatePlaceRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CreatePlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.objectName = objectName;
            inValue.Body.alias = alias;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            inValue.Body.activePlaceId = activePlaceId;
            inValue.Body.pos = pos;
            W2W.TaskEmail.ServiceReference1.CreatePlaceResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CreatePlace(inValue);
            return retVal.Body.CreatePlaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreatePlaceResponse> W2W.TaskEmail.ServiceReference1.IService1.CreatePlaceAsync(W2W.TaskEmail.ServiceReference1.CreatePlaceRequest request) {
            return base.Channel.CreatePlaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CreatePlaceResponse> CreatePlaceAsync(uint companyId, uint marketingId, uint partnerId, string objectName, string alias, decimal sum, System.DateTime date, string user, uint activePlaceId, int pos) {
            W2W.TaskEmail.ServiceReference1.CreatePlaceRequest inValue = new W2W.TaskEmail.ServiceReference1.CreatePlaceRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CreatePlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.objectName = objectName;
            inValue.Body.alias = alias;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            inValue.Body.activePlaceId = activePlaceId;
            inValue.Body.pos = pos;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CreatePlaceAsync(inValue);
        }
        
        public int UpdateBalances() {
            return base.Channel.UpdateBalances();
        }
        
        public System.Threading.Tasks.Task<int> UpdateBalancesAsync() {
            return base.Channel.UpdateBalancesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse W2W.TaskEmail.ServiceReference1.IService1.ConfirmWithdrawal(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest request) {
            return base.Channel.ConfirmWithdrawal(request);
        }
        
        public void ConfirmWithdrawal(uint id_object, string wallet, string tag, string comment, string user) {
            W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest inValue = new W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.wallet = wallet;
            inValue.Body.tag = tag;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).ConfirmWithdrawal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse> W2W.TaskEmail.ServiceReference1.IService1.ConfirmWithdrawalAsync(W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest request) {
            return base.Channel.ConfirmWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(uint id_object, string wallet, string tag, string comment, string user) {
            W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest inValue = new W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.ConfirmWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.wallet = wallet;
            inValue.Body.tag = tag;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).ConfirmWithdrawalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse W2W.TaskEmail.ServiceReference1.IService1.CancelWithdrawal(W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest request) {
            return base.Channel.CancelWithdrawal(request);
        }
        
        public void CancelWithdrawal(uint id_object, string comment, string user) {
            W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest inValue = new W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CancelWithdrawal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse> W2W.TaskEmail.ServiceReference1.IService1.CancelWithdrawalAsync(W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest request) {
            return base.Channel.CancelWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.CancelWithdrawalResponse> CancelWithdrawalAsync(uint id_object, string comment, string user) {
            W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest inValue = new W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.CancelWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).CancelWithdrawalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse W2W.TaskEmail.ServiceReference1.IService1.UnionInvestments(W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest request) {
            return base.Channel.UnionInvestments(request);
        }
        
        public void UnionInvestments(uint companyId, uint partnerId, decimal sum, W2W.TaskEmail.ServiceReference1.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest inValue = new W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.investments = investments;
            inValue.Body.date = date;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).UnionInvestments(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse> W2W.TaskEmail.ServiceReference1.IService1.UnionInvestmentsAsync(W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest request) {
            return base.Channel.UnionInvestmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.UnionInvestmentsResponse> UnionInvestmentsAsync(uint companyId, uint partnerId, decimal sum, W2W.TaskEmail.ServiceReference1.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest inValue = new W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.UnionInvestmentsRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.investments = investments;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).UnionInvestmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse W2W.TaskEmail.ServiceReference1.IService1.TerminateInvestment(W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest request) {
            return base.Channel.TerminateInvestment(request);
        }
        
        public void TerminateInvestment(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user, System.Nullable<bool> isNotClose) {
            W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest inValue = new W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.investmentId = investmentId;
            inValue.Body.returnSum = returnSum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            inValue.Body.isNotClose = isNotClose;
            W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).TerminateInvestment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse> W2W.TaskEmail.ServiceReference1.IService1.TerminateInvestmentAsync(W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest request) {
            return base.Channel.TerminateInvestmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.TerminateInvestmentResponse> TerminateInvestmentAsync(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user, System.Nullable<bool> isNotClose) {
            W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest inValue = new W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.TerminateInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.investmentId = investmentId;
            inValue.Body.returnSum = returnSum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            inValue.Body.isNotClose = isNotClose;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).TerminateInvestmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        W2W.TaskEmail.ServiceReference1.SendEmailResponse W2W.TaskEmail.ServiceReference1.IService1.SendEmail(W2W.TaskEmail.ServiceReference1.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public void SendEmail(uint companyId, string user) {
            W2W.TaskEmail.ServiceReference1.SendEmailRequest inValue = new W2W.TaskEmail.ServiceReference1.SendEmailRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.SendEmailRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            W2W.TaskEmail.ServiceReference1.SendEmailResponse retVal = ((W2W.TaskEmail.ServiceReference1.IService1)(this)).SendEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.SendEmailResponse> W2W.TaskEmail.ServiceReference1.IService1.SendEmailAsync(W2W.TaskEmail.ServiceReference1.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<W2W.TaskEmail.ServiceReference1.SendEmailResponse> SendEmailAsync(uint companyId, string user) {
            W2W.TaskEmail.ServiceReference1.SendEmailRequest inValue = new W2W.TaskEmail.ServiceReference1.SendEmailRequest();
            inValue.Body = new W2W.TaskEmail.ServiceReference1.SendEmailRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            return ((W2W.TaskEmail.ServiceReference1.IService1)(this)).SendEmailAsync(inValue);
        }
    }
}
