//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WayWealth.Marketing {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUnsignedInt", Namespace="http://tempuri.org/", ItemName="unsignedInt")]
    [System.SerializableAttribute()]
    public class ArrayOfUnsignedInt : System.Collections.Generic.List<uint> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Marketing.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
        WayWealth.Marketing.BuyCamulativeResponse BuyCamulative(WayWealth.Marketing.BuyCamulativeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCamulative", ReplyAction="http://tempuri.org/IService1/BuyCamulativeResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.BuyCamulativeResponse> BuyCamulativeAsync(WayWealth.Marketing.BuyCamulativeRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
        WayWealth.Marketing.BuyInvestmentResponse BuyInvestment(WayWealth.Marketing.BuyInvestmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyInvestment", ReplyAction="http://tempuri.org/IService1/BuyInvestmentResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.BuyInvestmentResponse> BuyInvestmentAsync(WayWealth.Marketing.BuyInvestmentRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
        WayWealth.Marketing.PayInvestPercentsResponse PayInvestPercents(WayWealth.Marketing.PayInvestPercentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayInvestPercents", ReplyAction="http://tempuri.org/IService1/PayInvestPercentsResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.PayInvestPercentsResponse> PayInvestPercentsAsync(WayWealth.Marketing.PayInvestPercentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
        bool IsAllowCreateNewPlace(uint marketingId, uint partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsAllowCreateNewPlace", ReplyAction="http://tempuri.org/IService1/IsAllowCreateNewPlaceResponse")]
        System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
        WayWealth.Marketing.CreateTechPlaceResponse CreateTechPlace(WayWealth.Marketing.CreateTechPlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateTechPlace", ReplyAction="http://tempuri.org/IService1/CreateTechPlaceResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.CreateTechPlaceResponse> CreateTechPlaceAsync(WayWealth.Marketing.CreateTechPlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
        int UpdateBalances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBalances", ReplyAction="http://tempuri.org/IService1/UpdateBalancesResponse")]
        System.Threading.Tasks.Task<int> UpdateBalancesAsync();
        
        // CODEGEN: Generating message contract since element name wallet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
        WayWealth.Marketing.ConfirmWithdrawalResponse ConfirmWithdrawal(WayWealth.Marketing.ConfirmWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConfirmWithdrawal", ReplyAction="http://tempuri.org/IService1/ConfirmWithdrawalResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(WayWealth.Marketing.ConfirmWithdrawalRequest request);
        
        // CODEGEN: Generating message contract since element name comment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
        WayWealth.Marketing.CancelWithdrawalResponse CancelWithdrawal(WayWealth.Marketing.CancelWithdrawalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelWithdrawal", ReplyAction="http://tempuri.org/IService1/CancelWithdrawalResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.CancelWithdrawalResponse> CancelWithdrawalAsync(WayWealth.Marketing.CancelWithdrawalRequest request);
        
        // CODEGEN: Generating message contract since element name investments from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
        WayWealth.Marketing.UnionInvestmentsResponse UnionInvestments(WayWealth.Marketing.UnionInvestmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnionInvestments", ReplyAction="http://tempuri.org/IService1/UnionInvestmentsResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.UnionInvestmentsResponse> UnionInvestmentsAsync(WayWealth.Marketing.UnionInvestmentsRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
        WayWealth.Marketing.TerminateInvestmentResponse TerminateInvestment(WayWealth.Marketing.TerminateInvestmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerminateInvestment", ReplyAction="http://tempuri.org/IService1/TerminateInvestmentResponse")]
        System.Threading.Tasks.Task<WayWealth.Marketing.TerminateInvestmentResponse> TerminateInvestmentAsync(WayWealth.Marketing.TerminateInvestmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyCamulativeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulative", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.BuyCamulativeRequestBody Body;
        
        public BuyCamulativeRequest() {
        }
        
        public BuyCamulativeRequest(WayWealth.Marketing.BuyCamulativeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyCamulativeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint marketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        public BuyCamulativeRequestBody() {
        }
        
        public BuyCamulativeRequestBody(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            this.companyId = companyId;
            this.marketingId = marketingId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyCamulativeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyCamulativeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.BuyCamulativeResponseBody Body;
        
        public BuyCamulativeResponse() {
        }
        
        public BuyCamulativeResponse(WayWealth.Marketing.BuyCamulativeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyCamulativeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint BuyCamulativeResult;
        
        public BuyCamulativeResponseBody() {
        }
        
        public BuyCamulativeResponseBody(uint BuyCamulativeResult) {
            this.BuyCamulativeResult = BuyCamulativeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyInvestmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestment", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.BuyInvestmentRequestBody Body;
        
        public BuyInvestmentRequest() {
        }
        
        public BuyInvestmentRequest(WayWealth.Marketing.BuyInvestmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyInvestmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint camulativeMarketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isProlonged;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isCreateNewPlace;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string user;
        
        public BuyInvestmentRequestBody() {
        }
        
        public BuyInvestmentRequestBody(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            this.companyId = companyId;
            this.camulativeMarketingId = camulativeMarketingId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.isProlonged = isProlonged;
            this.isCreateNewPlace = isCreateNewPlace;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuyInvestmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.BuyInvestmentResponseBody Body;
        
        public BuyInvestmentResponse() {
        }
        
        public BuyInvestmentResponse(WayWealth.Marketing.BuyInvestmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuyInvestmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint BuyInvestmentResult;
        
        public BuyInvestmentResponseBody() {
        }
        
        public BuyInvestmentResponseBody(uint BuyInvestmentResult) {
            this.BuyInvestmentResult = BuyInvestmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayInvestPercentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercents", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.PayInvestPercentsRequestBody Body;
        
        public PayInvestPercentsRequest() {
        }
        
        public PayInvestPercentsRequest(WayWealth.Marketing.PayInvestPercentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayInvestPercentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public PayInvestPercentsRequestBody() {
        }
        
        public PayInvestPercentsRequestBody(System.DateTime date, uint companyId, string user) {
            this.date = date;
            this.companyId = companyId;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayInvestPercentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayInvestPercentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.PayInvestPercentsResponseBody Body;
        
        public PayInvestPercentsResponse() {
        }
        
        public PayInvestPercentsResponse(WayWealth.Marketing.PayInvestPercentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayInvestPercentsResponseBody {
        
        public PayInvestPercentsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTechPlaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlace", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.CreateTechPlaceRequestBody Body;
        
        public CreateTechPlaceRequest() {
        }
        
        public CreateTechPlaceRequest(WayWealth.Marketing.CreateTechPlaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTechPlaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint marketingId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string user;
        
        public CreateTechPlaceRequestBody() {
        }
        
        public CreateTechPlaceRequestBody(uint companyId, uint marketingId, System.DateTime date, string user) {
            this.companyId = companyId;
            this.marketingId = marketingId;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTechPlaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTechPlaceResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.CreateTechPlaceResponseBody Body;
        
        public CreateTechPlaceResponse() {
        }
        
        public CreateTechPlaceResponse(WayWealth.Marketing.CreateTechPlaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTechPlaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint CreateTechPlaceResult;
        
        public CreateTechPlaceResponseBody() {
        }
        
        public CreateTechPlaceResponseBody(uint CreateTechPlaceResult) {
            this.CreateTechPlaceResult = CreateTechPlaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawal", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.ConfirmWithdrawalRequestBody Body;
        
        public ConfirmWithdrawalRequest() {
        }
        
        public ConfirmWithdrawalRequest(WayWealth.Marketing.ConfirmWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint id_object;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string wallet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string user;
        
        public ConfirmWithdrawalRequestBody() {
        }
        
        public ConfirmWithdrawalRequestBody(uint id_object, string wallet, string tag, string comment, string user) {
            this.id_object = id_object;
            this.wallet = wallet;
            this.tag = tag;
            this.comment = comment;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmWithdrawalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.ConfirmWithdrawalResponseBody Body;
        
        public ConfirmWithdrawalResponse() {
        }
        
        public ConfirmWithdrawalResponse(WayWealth.Marketing.ConfirmWithdrawalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConfirmWithdrawalResponseBody {
        
        public ConfirmWithdrawalResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelWithdrawalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawal", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.CancelWithdrawalRequestBody Body;
        
        public CancelWithdrawalRequest() {
        }
        
        public CancelWithdrawalRequest(WayWealth.Marketing.CancelWithdrawalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelWithdrawalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint id_object;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public CancelWithdrawalRequestBody() {
        }
        
        public CancelWithdrawalRequestBody(uint id_object, string comment, string user) {
            this.id_object = id_object;
            this.comment = comment;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelWithdrawalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelWithdrawalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.CancelWithdrawalResponseBody Body;
        
        public CancelWithdrawalResponse() {
        }
        
        public CancelWithdrawalResponse(WayWealth.Marketing.CancelWithdrawalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CancelWithdrawalResponseBody {
        
        public CancelWithdrawalResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnionInvestmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestments", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.UnionInvestmentsRequestBody Body;
        
        public UnionInvestmentsRequest() {
        }
        
        public UnionInvestmentsRequest(WayWealth.Marketing.UnionInvestmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnionInvestmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WayWealth.Marketing.ArrayOfUnsignedInt investments;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        public UnionInvestmentsRequestBody() {
        }
        
        public UnionInvestmentsRequestBody(uint companyId, uint partnerId, decimal sum, WayWealth.Marketing.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            this.companyId = companyId;
            this.partnerId = partnerId;
            this.sum = sum;
            this.investments = investments;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnionInvestmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnionInvestmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.UnionInvestmentsResponseBody Body;
        
        public UnionInvestmentsResponse() {
        }
        
        public UnionInvestmentsResponse(WayWealth.Marketing.UnionInvestmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UnionInvestmentsResponseBody {
        
        public UnionInvestmentsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateInvestmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestment", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.TerminateInvestmentRequestBody Body;
        
        public TerminateInvestmentRequest() {
        }
        
        public TerminateInvestmentRequest(WayWealth.Marketing.TerminateInvestmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TerminateInvestmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public uint investmentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal returnSum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user;
        
        public TerminateInvestmentRequestBody() {
        }
        
        public TerminateInvestmentRequestBody(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user) {
            this.companyId = companyId;
            this.partnerId = partnerId;
            this.investmentId = investmentId;
            this.returnSum = returnSum;
            this.date = date;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateInvestmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TerminateInvestmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WayWealth.Marketing.TerminateInvestmentResponseBody Body;
        
        public TerminateInvestmentResponse() {
        }
        
        public TerminateInvestmentResponse(WayWealth.Marketing.TerminateInvestmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TerminateInvestmentResponseBody {
        
        public TerminateInvestmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WayWealth.Marketing.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WayWealth.Marketing.IService1>, WayWealth.Marketing.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.BuyCamulativeResponse WayWealth.Marketing.IService1.BuyCamulative(WayWealth.Marketing.BuyCamulativeRequest request) {
            return base.Channel.BuyCamulative(request);
        }
        
        public uint BuyCamulative(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            WayWealth.Marketing.BuyCamulativeRequest inValue = new WayWealth.Marketing.BuyCamulativeRequest();
            inValue.Body = new WayWealth.Marketing.BuyCamulativeRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            WayWealth.Marketing.BuyCamulativeResponse retVal = ((WayWealth.Marketing.IService1)(this)).BuyCamulative(inValue);
            return retVal.Body.BuyCamulativeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.BuyCamulativeResponse> WayWealth.Marketing.IService1.BuyCamulativeAsync(WayWealth.Marketing.BuyCamulativeRequest request) {
            return base.Channel.BuyCamulativeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.BuyCamulativeResponse> BuyCamulativeAsync(uint companyId, uint marketingId, uint partnerId, decimal sum, System.DateTime date, string user) {
            WayWealth.Marketing.BuyCamulativeRequest inValue = new WayWealth.Marketing.BuyCamulativeRequest();
            inValue.Body = new WayWealth.Marketing.BuyCamulativeRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).BuyCamulativeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.BuyInvestmentResponse WayWealth.Marketing.IService1.BuyInvestment(WayWealth.Marketing.BuyInvestmentRequest request) {
            return base.Channel.BuyInvestment(request);
        }
        
        public uint BuyInvestment(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            WayWealth.Marketing.BuyInvestmentRequest inValue = new WayWealth.Marketing.BuyInvestmentRequest();
            inValue.Body = new WayWealth.Marketing.BuyInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.camulativeMarketingId = camulativeMarketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.isProlonged = isProlonged;
            inValue.Body.isCreateNewPlace = isCreateNewPlace;
            inValue.Body.date = date;
            inValue.Body.user = user;
            WayWealth.Marketing.BuyInvestmentResponse retVal = ((WayWealth.Marketing.IService1)(this)).BuyInvestment(inValue);
            return retVal.Body.BuyInvestmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.BuyInvestmentResponse> WayWealth.Marketing.IService1.BuyInvestmentAsync(WayWealth.Marketing.BuyInvestmentRequest request) {
            return base.Channel.BuyInvestmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.BuyInvestmentResponse> BuyInvestmentAsync(uint companyId, uint camulativeMarketingId, uint partnerId, decimal sum, bool isProlonged, bool isCreateNewPlace, System.DateTime date, string user) {
            WayWealth.Marketing.BuyInvestmentRequest inValue = new WayWealth.Marketing.BuyInvestmentRequest();
            inValue.Body = new WayWealth.Marketing.BuyInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.camulativeMarketingId = camulativeMarketingId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.isProlonged = isProlonged;
            inValue.Body.isCreateNewPlace = isCreateNewPlace;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).BuyInvestmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.PayInvestPercentsResponse WayWealth.Marketing.IService1.PayInvestPercents(WayWealth.Marketing.PayInvestPercentsRequest request) {
            return base.Channel.PayInvestPercents(request);
        }
        
        public void PayInvestPercents(System.DateTime date, uint companyId, string user) {
            WayWealth.Marketing.PayInvestPercentsRequest inValue = new WayWealth.Marketing.PayInvestPercentsRequest();
            inValue.Body = new WayWealth.Marketing.PayInvestPercentsRequestBody();
            inValue.Body.date = date;
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            WayWealth.Marketing.PayInvestPercentsResponse retVal = ((WayWealth.Marketing.IService1)(this)).PayInvestPercents(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.PayInvestPercentsResponse> WayWealth.Marketing.IService1.PayInvestPercentsAsync(WayWealth.Marketing.PayInvestPercentsRequest request) {
            return base.Channel.PayInvestPercentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.PayInvestPercentsResponse> PayInvestPercentsAsync(System.DateTime date, uint companyId, string user) {
            WayWealth.Marketing.PayInvestPercentsRequest inValue = new WayWealth.Marketing.PayInvestPercentsRequest();
            inValue.Body = new WayWealth.Marketing.PayInvestPercentsRequestBody();
            inValue.Body.date = date;
            inValue.Body.companyId = companyId;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).PayInvestPercentsAsync(inValue);
        }
        
        public bool IsAllowCreateNewPlace(uint marketingId, uint partnerId) {
            return base.Channel.IsAllowCreateNewPlace(marketingId, partnerId);
        }
        
        public System.Threading.Tasks.Task<bool> IsAllowCreateNewPlaceAsync(uint marketingId, uint partnerId) {
            return base.Channel.IsAllowCreateNewPlaceAsync(marketingId, partnerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.CreateTechPlaceResponse WayWealth.Marketing.IService1.CreateTechPlace(WayWealth.Marketing.CreateTechPlaceRequest request) {
            return base.Channel.CreateTechPlace(request);
        }
        
        public uint CreateTechPlace(uint companyId, uint marketingId, System.DateTime date, string user) {
            WayWealth.Marketing.CreateTechPlaceRequest inValue = new WayWealth.Marketing.CreateTechPlaceRequest();
            inValue.Body = new WayWealth.Marketing.CreateTechPlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.date = date;
            inValue.Body.user = user;
            WayWealth.Marketing.CreateTechPlaceResponse retVal = ((WayWealth.Marketing.IService1)(this)).CreateTechPlace(inValue);
            return retVal.Body.CreateTechPlaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.CreateTechPlaceResponse> WayWealth.Marketing.IService1.CreateTechPlaceAsync(WayWealth.Marketing.CreateTechPlaceRequest request) {
            return base.Channel.CreateTechPlaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.CreateTechPlaceResponse> CreateTechPlaceAsync(uint companyId, uint marketingId, System.DateTime date, string user) {
            WayWealth.Marketing.CreateTechPlaceRequest inValue = new WayWealth.Marketing.CreateTechPlaceRequest();
            inValue.Body = new WayWealth.Marketing.CreateTechPlaceRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.marketingId = marketingId;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).CreateTechPlaceAsync(inValue);
        }
        
        public int UpdateBalances() {
            return base.Channel.UpdateBalances();
        }
        
        public System.Threading.Tasks.Task<int> UpdateBalancesAsync() {
            return base.Channel.UpdateBalancesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.ConfirmWithdrawalResponse WayWealth.Marketing.IService1.ConfirmWithdrawal(WayWealth.Marketing.ConfirmWithdrawalRequest request) {
            return base.Channel.ConfirmWithdrawal(request);
        }
        
        public void ConfirmWithdrawal(uint id_object, string wallet, string tag, string comment, string user) {
            WayWealth.Marketing.ConfirmWithdrawalRequest inValue = new WayWealth.Marketing.ConfirmWithdrawalRequest();
            inValue.Body = new WayWealth.Marketing.ConfirmWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.wallet = wallet;
            inValue.Body.tag = tag;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            WayWealth.Marketing.ConfirmWithdrawalResponse retVal = ((WayWealth.Marketing.IService1)(this)).ConfirmWithdrawal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.ConfirmWithdrawalResponse> WayWealth.Marketing.IService1.ConfirmWithdrawalAsync(WayWealth.Marketing.ConfirmWithdrawalRequest request) {
            return base.Channel.ConfirmWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.ConfirmWithdrawalResponse> ConfirmWithdrawalAsync(uint id_object, string wallet, string tag, string comment, string user) {
            WayWealth.Marketing.ConfirmWithdrawalRequest inValue = new WayWealth.Marketing.ConfirmWithdrawalRequest();
            inValue.Body = new WayWealth.Marketing.ConfirmWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.wallet = wallet;
            inValue.Body.tag = tag;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).ConfirmWithdrawalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.CancelWithdrawalResponse WayWealth.Marketing.IService1.CancelWithdrawal(WayWealth.Marketing.CancelWithdrawalRequest request) {
            return base.Channel.CancelWithdrawal(request);
        }
        
        public void CancelWithdrawal(uint id_object, string comment, string user) {
            WayWealth.Marketing.CancelWithdrawalRequest inValue = new WayWealth.Marketing.CancelWithdrawalRequest();
            inValue.Body = new WayWealth.Marketing.CancelWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            WayWealth.Marketing.CancelWithdrawalResponse retVal = ((WayWealth.Marketing.IService1)(this)).CancelWithdrawal(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.CancelWithdrawalResponse> WayWealth.Marketing.IService1.CancelWithdrawalAsync(WayWealth.Marketing.CancelWithdrawalRequest request) {
            return base.Channel.CancelWithdrawalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.CancelWithdrawalResponse> CancelWithdrawalAsync(uint id_object, string comment, string user) {
            WayWealth.Marketing.CancelWithdrawalRequest inValue = new WayWealth.Marketing.CancelWithdrawalRequest();
            inValue.Body = new WayWealth.Marketing.CancelWithdrawalRequestBody();
            inValue.Body.id_object = id_object;
            inValue.Body.comment = comment;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).CancelWithdrawalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.UnionInvestmentsResponse WayWealth.Marketing.IService1.UnionInvestments(WayWealth.Marketing.UnionInvestmentsRequest request) {
            return base.Channel.UnionInvestments(request);
        }
        
        public void UnionInvestments(uint companyId, uint partnerId, decimal sum, WayWealth.Marketing.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            WayWealth.Marketing.UnionInvestmentsRequest inValue = new WayWealth.Marketing.UnionInvestmentsRequest();
            inValue.Body = new WayWealth.Marketing.UnionInvestmentsRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.investments = investments;
            inValue.Body.date = date;
            inValue.Body.user = user;
            WayWealth.Marketing.UnionInvestmentsResponse retVal = ((WayWealth.Marketing.IService1)(this)).UnionInvestments(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.UnionInvestmentsResponse> WayWealth.Marketing.IService1.UnionInvestmentsAsync(WayWealth.Marketing.UnionInvestmentsRequest request) {
            return base.Channel.UnionInvestmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.UnionInvestmentsResponse> UnionInvestmentsAsync(uint companyId, uint partnerId, decimal sum, WayWealth.Marketing.ArrayOfUnsignedInt investments, System.DateTime date, string user) {
            WayWealth.Marketing.UnionInvestmentsRequest inValue = new WayWealth.Marketing.UnionInvestmentsRequest();
            inValue.Body = new WayWealth.Marketing.UnionInvestmentsRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.sum = sum;
            inValue.Body.investments = investments;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).UnionInvestmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WayWealth.Marketing.TerminateInvestmentResponse WayWealth.Marketing.IService1.TerminateInvestment(WayWealth.Marketing.TerminateInvestmentRequest request) {
            return base.Channel.TerminateInvestment(request);
        }
        
        public void TerminateInvestment(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user) {
            WayWealth.Marketing.TerminateInvestmentRequest inValue = new WayWealth.Marketing.TerminateInvestmentRequest();
            inValue.Body = new WayWealth.Marketing.TerminateInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.investmentId = investmentId;
            inValue.Body.returnSum = returnSum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            WayWealth.Marketing.TerminateInvestmentResponse retVal = ((WayWealth.Marketing.IService1)(this)).TerminateInvestment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WayWealth.Marketing.TerminateInvestmentResponse> WayWealth.Marketing.IService1.TerminateInvestmentAsync(WayWealth.Marketing.TerminateInvestmentRequest request) {
            return base.Channel.TerminateInvestmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WayWealth.Marketing.TerminateInvestmentResponse> TerminateInvestmentAsync(uint companyId, uint partnerId, uint investmentId, decimal returnSum, System.DateTime date, string user) {
            WayWealth.Marketing.TerminateInvestmentRequest inValue = new WayWealth.Marketing.TerminateInvestmentRequest();
            inValue.Body = new WayWealth.Marketing.TerminateInvestmentRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.partnerId = partnerId;
            inValue.Body.investmentId = investmentId;
            inValue.Body.returnSum = returnSum;
            inValue.Body.date = date;
            inValue.Body.user = user;
            return ((WayWealth.Marketing.IService1)(this)).TerminateInvestmentAsync(inValue);
        }
    }
}
